### PR TITLE
MAINT: Update GHA and test preview mechanism

### PR DESCRIPTION
**Pull request by mmcky**
This PR

- [x] updates workflow versions
- [x] tests preview and netlify setup

### CODE REVIEW

**Comment by mmcky** [comment]
@HumphreyYang just checking you don't need `_config.ymla` do you? I have removed it in [00c8bfa](https://github.com/QuantEcon/lecture-stats/pull/2/commits/00c8bfa8d9fc2d93a6236b03f5a9b9c1ffd6513b)

**Comment by HumphreyYang** [comment]
> @HumphreyYang just checking you don't need `_config.ymla` do you? I have removed it in [00c8bfa](https://github.com/QuantEcon/lecture-stats/pull/2/commits/00c8bfa8d9fc2d93a6236b03f5a9b9c1ffd6513b)

Many thanks @mmcky. No, we don’t need it. 

Please be aware that the lecture on AR(1) processes might be moved to the intro series. Let’s publish this lecture after I hear back from John : )

**Comment by mmcky** [comment]
> Many thanks @mmcky. No, we don’t need it.

👍 

@HumphreyYang I am just getting all the infrastructure setup and tested. 
I won't be setting up the `url` structure until the last step.

**Comment by HumphreyYang** [comment]
> @HumphreyYang I am just getting all the infrastructure setup and tested. I won't be setting up the `url` structure until the last step.

Many thanks @mmcky, roger that.

**Pull request merged**
