### PR TITLE
[bayes_nonconj] Remove `pyro` code from bayes_nonconj

### LINKED ISSUE #13: [bayes_nonconj] Migrate from pytorch to just use JAX
The lecture `bayes_conconj` uses `pytorch`. This causes software issues between `pytorch` and `jax` as they don't reference the same CUDA and CUDANN drivers or version. They are not compatible with each other in the same software context for CUDA v12. 

https://github.com/google/jax/issues/18032

Is it feasible to update this lecture to only use JAX and remove `pytorch` as a dependency? It is the only lecture to use `pytorch` 

- [x] remove `torch` as a dependency
- [ ] remove `pyro` as a dependency

@kp992 would you be able to look into this?

--- 

## Infrastructure Updates:

- [x] update from `cuda-11.8.0-anaconda-2023-09-py311` to `cuda-12.3.1-anaconda-2023-09-py311`
- [ ] lower cloud `hdd` from `100` to `40` GB

### PR DESCRIPTION
**Pull request by kp992**
Fixes #13 

cc @mmcky

### CODE REVIEW

**Comment by kp992** [comment]
@mmcky Can you please test it if there are no clashes between JAX/torch GPU? Many thanks.

**Comment by mmcky** [comment]
@kp992 exceptional work on removing `pyro`. 

It actually has simplified the code a lot. 

I will ask @thomassargent30 to take a look at the preview https://65c7800b5289ee700011359b--timely-seahorse-68815c.netlify.app/bayes_nonconj

**Comment by mmcky** [comment]
@thomassargent30 -- when setting up this series of lectures, we found that this lecture `bayes_nonconj`  used `jax` and `pytorch` which causes major issues when using the same software environment -- which is why even on https://python.quantecon.org/bayes_nonconj.html it was computing using a `cpu`. Essentially `torch` and `jax` seem incompatible due to conflicts in a mix of CUDA / GPU driver versions and therefore require different drivers which can't be done in the same software environment. 

@kp992 has done a great job of removing `torch` and focusing this lecture just on `jax` which removes the dependency on `torch`. 

Would you be able to review

https://65c7800b5289ee700011359b--timely-seahorse-68815c.netlify.app/bayes_nonconj

when you have time. 

This should fix the last major technical issue in the `reorg` project.

**Comment by mmcky** [comment]
thanks @kp992 and @thomassargent30. Merging this now.

**Pull request merged**
