### PR TITLE
FIX: Update CUDA and improve status page with diagnostics

### LINKED ISSUE #10: BUG: CUDA + JAX
There is a compatibility with CUDA and JAX

```
CUDA backend failed to initialize: Found CUDA version 12010, but JAX was built against version 12020, which is newer. The copy of CUDA that is installed must be at least as new as the version against which JAX was built. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
```

### PR DESCRIPTION
**Pull request by mmcky**
fixes #10 #5

### CODE REVIEW

**Comment by mmcky** [comment]
- [x] rerun with `jax[_local]` installed instead of `jax[_pip]` as per [9f96343](https://github.com/QuantEcon/lecture-python.docker/commit/9f963435a0c996f7b57a8d81d80c947b8702c5c5)

**Comment by mmcky** [comment]
- [x] re-run with latest docker (switched numpyro and jax) -- it looks like `numpyro` is causing linking issues in jax.

**Comment by mmcky** [comment]
@HumphreyYang this is now installing `torch` and `pyro-ppl` in the Docker container then installing `jax` to ensure appropriate CUDA linking for JAX. It is running with `gpu` enabled as reported in https://65bc2ecf929de00cbf2d4378--timely-seahorse-68815c.netlify.app/status

I am surprised though to see the runtime now 5000s so maybe torch is not working as expected. 

- [x] build a CUDA=12.1 docker image with `torch`, `pyro-ppl` and `jax` to see if we can improve the runtime with proper driver linking. We need to install `jax` in the 12.1 context without 12.3 driver downloads as a `whl`

**Update:** the above configuration still has an issue with `pytorch` and `jax` in the same `conda` environment. I have just come across the following: 
https://github.com/google/jax/issues/18032
so it is a known issue that is currently not resolved. I think what we have now using `CUDA=12.3` might be the best we can achieve without loading two separate conda environments (at the lecture lecture).

**Comment by mmcky** [comment]
- [x] test CUDA=11.8 as both work in that context

down from 7 to 1 incompatible dependency between the two

```
torch 2.2.0+cu118 requires nvidia-cudnn-cu11==8.7.0.84; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cudnn-cu11 8.9.6.50 which is incompatible.
```

- [x] need to review where docker is running out of memory for this test. Doesn't appear linked to the `hdd` allocation

**Comment by mmcky** [comment]
- [ ] see if `bayes_nonconj` can be updated to remove the `pytorch` dependency and use `jax` instead https://github.com/QuantEcon/lecture-stats/issues/13

**Comment by mmcky** [comment]
- [ ] wait for #13 as it will remove two dependencies causing the issues of software conflicts. Then we can use the latest `CUDA` for JAX

**Comment by mmcky** [comment]
@kp992 I will merge this PR to remove the CUDA failure message that is currently live on `stats.quantecon.org` and then I will open an issue to update the docker image to use `mmcky/quantecon-lecture-python:cuda-12.3.1-anaconda-2023-09-py311` once we have removed `pytorch` and `pyro` successfully.

**Comment by kp992** [comment]
Sounds good to me. Thanks @mmcky

**Pull request merged**
